name: Develop Test, Build and Deploy Workflow

on:
  push:
    branches: [devops-develop]
  pull_request:
    branches: [dev]
    types: [opened, reopened, synchronize, closed]

jobs:
  first_step:
    if: github.ref != 'refs/heads/devops-develop'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
      - name: Log something to the console
        run: echo 'First something'
      - name: 'cat package.json'
        run: cat ./package.json

  update_version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged || github.ref == 'refs/heads/devops-develop'
    needs: [first_step]
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: 'dev'
      - name: 'Automated Version Bump'
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording: '[MAJOR]'
          minor-wording: '[MINOR]'
          target-branch: dev


  last_step:
    if: github.event.pull_request.merged || github.ref == 'refs/heads/devops-develop'
    runs-on: ubuntu-latest
    needs: [first_step, update_version]
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          ref: 'dev'
      - name: Log something to the console
        run: echo 'Last something'
      - name: 'cat package.json'
        run: cat ./package.json
