name: Develop Test, Build and Deploy Workflow

on:
  push:
    branches: [devops-develop]
  pull_request:
    branches: [dev]
    types: [opened, reopened, synchronize, closed]

jobs:
  first_step:
    if: github.ref != 'refs/heads/devops-develop'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
      - name: Log something to the console
        run: echo 'First something'
      - name: 'cat package.json'
        run: cat ./package.json

  # update_version:
  #   runs-on: ubuntu-latest
  #   if: github.event.pull_request.merged || github.ref == 'refs/heads/devops-develop'
  #   needs: [first_step]
  #   steps:
  #     - name: 'Checkout source code'
  #       uses: 'actions/checkout@v2'
  #       with:
  #         ref: 'dev'
  #     - name: 'Automated Version Bump'
  #       uses: phips28/gh-action-bump-version@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         major-wording: '[MAJOR]'
  #         minor-wording: '[MINOR]'
  #         target-branch: dev

  update_version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged || github.ref == 'refs/heads/devops-develop'
    needs: [first_step]
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
      - name: 'Automated Version Bump'
        uses: copapow/version-bump-package@v1
        with:
          default_branch: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: EndBug/add-and-commit@v7  
        with:
          branch: dev
          message: 'Bump package version'

  # update_version:
  #   runs-on: ubuntu-latest
  #   if: github.event.pull_request.merged || github.ref == 'refs/heads/devops-develop'
  #   needs: [first_step]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '16.15.0'
  #     - uses: fregante/setup-git-user@v1
  #     - name: Apply version bump (major)
  #       if: contains(github.event.pull_request.labels.*.name, 'major')
  #       run: npm version major
  #     - name: Apply version bump (minor)
  #       if: contains(github.event.pull_request.labels.*.name, 'minor')
  #       run: npm version minor
  #     - name: Apply version bump (patch)
  #       if: contains(github.event.pull_request.labels.*.name, 'patch')
  #       run: npm version patch
  #     - name: Git push version bump
  #       run: git push origin dev --follow-tags --force
  #     - id: set-version
  #       name: Output version change
  #       run: npm pkg get version


  last_step:
    if: github.event.pull_request.merged || github.ref == 'refs/heads/devops-develop'
    runs-on: ubuntu-latest
    needs: [first_step, update_version]
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          ref: 'dev'
      - name: Log something to the console
        run: echo 'Last something'
      - name: 'cat package.json'
        run: cat ./package.json
