name: Develop Test, Build and Deploy Workflow

on:
  push:
    branches: [devops-develop]
  pull_request:
    branches: [dev]
    types: [opened, reopened, synchronize, closed]

jobs:
  first_step:
    runs-on: ubuntu-latest
    steps:
      - name: Log something to the console
        run: echo 'First something'

  update_version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    needs: [first_step]
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
      - name: 'Automated Version Bump'
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording: '[MAJOR]'
          minor-wording: '[MINOR]'

  last_step:
    runs-on: ubuntu-latest
    needs: [first_step, update_version]
    steps:
      - name: Log something to the console
        run: echo 'Last something'
