name: Production Test, Build and Deploy Workflow

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, closed]
jobs:
  label_step:
    if: join(github.event.pull_request.labels) != ''
    runs-on: ubuntu-latest
    steps:
      - name: 'Log something to the console'
        run: echo ${{ github.event.pull_request.labels }}
  first_step:
    runs-on: ubuntu-latest
    steps:
      - name: Log something to the console
        run: echo 'First something'

  update_version:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/devops-develop' && join(github.event.pull_request.labels) != ''
    needs: [first_step]
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
      - name: 'Automated Version Bump'
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording: '[MAJOR]'
          minor-wording: '[MINOR]'

  last_step:
    runs-on: ubuntu-latest
    needs: [first_step]
    steps:
      - name: Log something to the console
        run: echo 'Last something'