name: Staging Test, Build and Deploy Workflow

on:
  push:
    branches: [devops-staging]
  pull_request:
    branches: [staging]
    types: [opened, reopened, synchronize, closed]

jobs:
  label_step:
    if: join(github.event.pull_request.labels) != ''
    runs-on: ubuntu-latest
    steps:
      - name: 'Log something to the console'
        run: echo 'LABELS: ${{ github.event.pull_request.labels }}'
  first_step:
    runs-on: ubuntu-latest
    steps:
      - name: Log something to the console
        run: echo 'First something'

  update_version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && join(github.event.pull_request.labels) != ''
    needs: [first_step]
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
      - name: 'Automated Version Bump'
        uses: copapow/version-bump-package@v1
        with:
          default_branch: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: EndBug/add-and-commit@v7  
        with:
          branch: dev
          message: 'Bump package version'


  last_step:
    if: github.event.pull_request.merged || github.ref == 'refs/heads/devops-staging'
    runs-on: ubuntu-latest
    needs: [first_step, update_version]
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          ref: 'staging'
      - name: Log something to the console
        run: echo 'Last something'
      - name: 'cat package.json'
        run: cat ./package.json
